theme: jekyll-theme-primer
title: Jasmine Studios
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
  
# Google Analytics
# google_analytics: UA-138756895-1

# Analytics
analytics:
  provider               : "google-gtag"
  google:
    measurement_id          : "G-C3MM12Q509"
    anonymize_ip         : # true, false (default)
