theme: jekyll-theme-primer
title: Jasmine Studios
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
  
# Google Analytics
# google_analytics: UA-138756895-1

# Analytics
google_analytics: G-C3MM12Q509
